apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: python-web-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/NavabShariff/python-web-app
    targetRevision: dev
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    syncOptions:
     - ApplyOutOfSync=true
    automated:
      selfHeal: true
    retry:
      limit: 1
      backoff:
        duration: 5s    # <-- Wait 5 seconds before first retry
        factor: 2       # <-- Multiply wait time by 2 on each retry
        maxDuration: 3m # <-- Maximum total wait time