apiVersion: v1
kind: Service
metadata:
  labels:
    app: python-webapp-svc
  name: python-webapp-svc
spec:
  ports:
  - name: python-web-app
    port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: python-web-app
  type: LoadBalancer