apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: python-web-app
  name: python-web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-web-app
  template:
    metadata:
      labels:
        app: python-web-app
    spec:
      containers:
      - image: navabnaeem/python-images:version-print
        name: python
        # command: 
        # - /bin/sh
        # - -c
        # - echo "Hello python"
        env:
        - name: APP_VERSION
          value: v6
      # restartPolicy: 
