# apiVersion: batch/v1
# kind: Job
# metadata:
#   name: vault-health-check
#   annotations:
#     # argocd.argoproj.io/hook: PreSync
#     # argocd.argoproj.io/hook: SyncFail
# spec:
#   backoffLimit: 0   # <--- No retries on failure
#   template:
#     spec:
#       containers:
#       - name: vault-check
#         image: curlimages/curl:latest
#         command: 
#         - /bin/sh
#         - -c
#         - |
#           if [ "$(curl -s -o /dev/null -w "%{http_code}" https://vault-ui.vault.svc.cluster.local/v1/sys/health)" -ne 200 ]; then
#             echo "Vault is not running properly. Exiting..."
#             exit 1
#           else
#             echo "Vault is up and running."
#           fi
#       restartPolicy: Never